export function getClientJs(currentModel?: string): string {
    const lines = [
        "(function() {",
        "    const vscode = acquireVsCodeApi();",
        "    ",
        "    function log(msg, detail) {",
        "        console.log('[Mosaic UI] ' + msg, detail || '');",
        "    }",
        "",
        "    class MosaicUI {",
        "        constructor() {",
        "            this.isGenerating = false;",
        "            this.assistantMessages = {};",
        `            this.currentModel = "${currentModel || ''}";`,
        "            this.init();",
        "        }",
        "",
        "        init() {",
        "            log('Initializing Event Delegation...');",
        "            ",
        "            document.addEventListener('click', (e) => {",
        "                const target = e.target.closest('button, .history-item, .tool-header, .thought-header');",
        "                if (!target) return;",
        "",
        "                if (target.id === 'action-button' || target.closest('#action-button')) {",
        "                    this.handleAction();",
        "                } else if (target.id === 'save-setup-btn') {",
        "                    this.handleSaveSetup();",
        "                } else if (target.id === 'history-btn' || target.closest('#history-btn')) {",
        "                    this.toggleModal('history-modal', 'listChats');",
        "                } else if (target.id === 'new-chat-btn' || target.closest('#new-chat-btn')) {",
        "                    vscode.postMessage({ type: 'resetChat' });",
        "                } else if (target.classList.contains('close-modal')) {",
        "                    const modalId = target.getAttribute('data-modal');",
        "                    if (modalId) document.getElementById(modalId).style.display = 'none';",
        "                } else if (target.classList.contains('history-item') && !target.classList.contains('task-item')) {",
        "                    if (target.classList.contains('confirming')) return;",
        "                    const chatId = target.getAttribute('data-id');",
        "                    if (chatId) {",
        "                        log('Loading Chat:', chatId);",
        "                        vscode.postMessage({ type: 'loadChat', value: chatId });",
        "                        document.getElementById('history-modal').style.display = 'none';",
        "                    }",
        "                } else if (target.classList.contains('tool-header') || target.classList.contains('thought-header')) {",
        "                    target.parentElement.classList.toggle('open');",
        "                }",
        "            });",
        "",
        "            document.addEventListener('keydown', (e) => {",
        "                if (e.target.id === 'chat-input') {",
        "                    if (e.key === 'Enter' && !e.shiftKey) {",
        "                        e.preventDefault();",
        "                        this.handleAction();",
        "                    }",
        "                }",
        "            });",
        "",
        "            document.addEventListener('input', (e) => {",
        "                if (e.target.id === 'chat-input') {",
        "                    const input = e.target;",
        "                    input.style.height = 'auto';",
        "                    input.style.height = input.scrollHeight + 'px';",
        "                }",
        "                if (e.target.id === 'setup-provider') {",
        "                    const apikeyGroup = document.getElementById('apikey-group');",
        "                    if (apikeyGroup) apikeyGroup.style.display = e.target.value === 'lmstudio' ? 'none' : 'block';",
        "                }",
        "            });",
        "",
        "            document.addEventListener('change', (e) => {",
        "                if (e.target.id === 'provider-select') {",
        "                    vscode.postMessage({ type: 'setProvider', value: e.target.value });",
        "                } else if (e.target.id === 'model-select') {",
        "                    vscode.postMessage({ type: 'setModel', value: e.target.value });",
        "                }",
        "            });",
        "",
        "            window.addEventListener('message', event => {",
        "                console.log('[Mosaic UI] 📥 Message from Extension:', event.data.type);",
        "                this.handleMessage(event.data);",
        "            });",
        "            ",
        "            if (document.getElementById('model-select')) {",
        "                vscode.postMessage({ type: 'fetchModels' });",
        "                vscode.postMessage({ type: 'getHistory' });",
        "            }",
        "            ",
        "            log('Mosaic UI Ready');",
        "        }",
        "",
        "        handleAction() {",
        "            const input = document.getElementById('chat-input');",
        "            if (this.isGenerating) {",
        "                vscode.postMessage({ type: 'stopGeneration' });",
        "            } else {",
        "                const text = input ? input.value.trim() : '';",
        "                if (text) {",
        "                    this.setGenerating(true);",
        "                    vscode.postMessage({ type: 'sendMessage', value: text });",
        "                    input.value = '';",
        "                    input.style.height = 'auto';",
        "                }",
        "            }",
        "        }",
        "",
        "        handleSaveSetup() {",
        "            const pEl = document.getElementById('setup-provider');",
        "            const kEl = document.getElementById('setup-apikey');",
        "            if (pEl) {",
        "                const p = pEl.value;",
        "                const k = kEl ? kEl.value : '';",
        "                vscode.postMessage({ type: 'setProvider', value: p });",
        "                if (k) vscode.postMessage({ type: 'setApiKey', value: k });",
        "            }",
        "        }",
        "",
        "        toggleModal(id, fetchType) {",
        "            const modal = document.getElementById(id);",
        "            const isVisible = modal && modal.style.display === 'block';",
        "            ",
        "            document.getElementById('history-modal').style.display = 'none';",
        "            ",
        "            if (modal && !isVisible) {",
        "                modal.style.display = 'block';",
        "                if (fetchType) vscode.postMessage({ type: fetchType });",
        "            }",
        "        }",
        "",
        "        setGenerating(val) {",
        "            this.isGenerating = val;",
        "            const btn = document.getElementById('action-button');",
        "            if (!btn) return;",
        "            btn.classList.toggle('generating', val);",
        "            btn.innerHTML = val ? '<span class=\"codicon codicon-debug-stop\"></span>' : '<span class=\"codicon codicon-send\"></span>';",
        "        }",
        "",
        "        handleMessage(msg) {",
        "            switch (msg.type) {",
        "                case 'addMessage': this.addMessage(msg.role, msg.content, msg.id); break;",
        "                case 'updateMessage': this.updateMessage(msg); break;",
        "                case 'generationFinished': this.setGenerating(false); break;",
        "                case 'setAvailableModels': this._updateModels(msg); break;",
        "                case 'generationMetadata': this.addMessageMetadata(msg.id, msg.metadata); break;",
        "                case 'chatList': this.updateChatList(msg.chats); break;",
        "                case 'todoList': this.updateTodoList(msg.todos); break;",
        "                case 'addSystemMessage': this.addSystemMessage(msg.content); break;",
        "                case 'clearMessages': ",
        "                    const container = document.getElementById('messages');",
        "                    if (container) container.innerHTML = ''; ",
        "                    break;",
        "            }",
        "        }",
        "",
        "        renderMarkdown(content) {",
        "            if (!content) return '';",
        "            ",
        "            if (Array.isArray(content)) {",
        "                return content.map(part => this.renderPart(part)).join('');",
        "            }",
        "            ",
        "            const blocks = [];",
        "            const blockRegex = /<(?<tag>thought|tool_call|tool_response|tool_result)[\\s\\S]*?(?:<\\/\\k<tag>>|$)/g;",
        "            ",
        "            let lastIdx = 0;",
        "            let match;",
        "            while ((match = blockRegex.exec(content)) !== null) {",
        "                if (match.index > lastIdx) {",
        "                    blocks.push({ type: 'message', content: content.substring(lastIdx, match.index) });",
        "                }",
        "                const tag = match.groups.tag;",
        "                let type = 'message';",
        "                if (tag === 'thought') type = 'thought';",
        "                else if (tag === 'tool_call') type = 'tool_call';",
        "                else if (tag === 'tool_response' || tag === 'tool_result') type = 'user_tool_result';",
        "                ",
        "                blocks.push({ type: type, content: match[0] });",
        "                lastIdx = blockRegex.lastIndex;",
        "            }",
        "            if (lastIdx < content.length) {",
        "                blocks.push({ type: 'message', content: content.substring(lastIdx) });",
        "            }",
        "",
        "            return blocks.map(b => this.renderPart(b)).join('');",
        "        }",
        "        ",
        "        renderPart(part) {",
        "            const { type, content } = part;",
        "            if (type === 'message') {",
        "                return typeof marked !== 'undefined' ? marked.parse(content) : content.replace(/\\n/g, '<br>');",
        "            }",
        "            ",
        "            if (type === 'thought') {",
        "                const isClosed = content.includes('</thought>');",
        "                const thoughtText = isClosed ? (content.match(/<thought>([\\s\\S]*?)<\\/thought>/)?.[1] || '') : content.substring(9);",
        "                return `<div class=\"thought-block ${!isClosed ? 'open' : ''}\"><div class=\"thought-header\"><span class=\"thought-icon codicon codicon-lightbulb\"></span> ${isClosed ? 'Thought' : 'Thinking...'}</div><div class=\"thought-content\">${typeof marked !== 'undefined' ? marked.parse(thoughtText.trim()) : thoughtText.trim()}</div></div>`;",
        "            }",
        "            ",
        "            if (type === 'tool_call') {",
        "                const isClosed = content.includes('</tool_call>');",
        "                if (isClosed) {",
        "                    const m = content.match(/<tool_call name=\"([^\"]+)\" id=\"([^\"]+)\">([\\s\\S]*?)<\\/tool_call>/);",
        "                    if (m) {",
        "                        const [_, name, id, args] = m;",
        "                        let summary = '';",
        "                        try {",
        "                            const parsed = JSON.parse(args.trim());",
        "                            if (name === 'run_command') summary = ': ' + (parsed.command || '');",
        "                            else if (parsed.path) summary = ': ' + parsed.path;",
        "                            else if (parsed.title) summary = ': ' + parsed.title;",
        "                        } catch(e) {}",
        "                        return `<div class=\"tool-call\" id=\"call-${id}\"><div class=\"tool-header loading\">${name.replace(/_/g, ' ')}${summary}</div><div class=\"tool-content\">${args.trim()}</div></div>`;",
        "                    }",
        "                } else {",
        "                    const m = content.match(/<tool_call name=\"([^\"]+)\" id=\"([^\"]+)\">([\\s\\S]*?)$/);",
        "                    if (m) {",
        "                        const [_, name] = m;",
        "                        return `<div class=\"tool-call loading\"><div class=\"tool-header loading\">Running ${name.replace(/_/g, ' ')}...</div></div>`;",
        "                    }",
        "                }",
        "            }",
        "            ",
        "            if (type === 'user_tool_result') {",
        "                const m = content.match(/<(?:tool_response|tool_result) id=\"([^\"]+)\">([\\s\\S]*?)<\\/(?:tool_response|tool_result)>/) || content.match(/<(?:tool_response|tool_result)>([\\s\\S]*?)<\\/(?:tool_response|tool_result)>/);",
        "                if (m) {",
        "                    const id = m[1] || '';",
        "                    const innerContent = m[2] || m[1];",
        "                    return `<div class=\"tool-result-marker\" data-id=\"${id}\" style=\"display:none\">${innerContent}</div>`;",
        "                }",
        "            }",
        "            ",
        "            return content;",
        "        }",
        "",
        "        finalizeToolCalls(container) {",
        "            const results = container.querySelectorAll('.tool-result-marker');",
        "            results.forEach(res => {",
        "                const id = res.getAttribute('data-id');",
        "                const callDiv = container.querySelector('#call-' + id) || (id ? document.getElementById('call-' + id) : null);",
        "                if (callDiv) {",
        "                    const header = callDiv.querySelector('.tool-header');",
        "                    const content = callDiv.querySelector('.tool-content');",
        "                    if (header) {",
        "                        header.classList.remove('loading');",
        "                        header.classList.add('done');",
        "                    }",
        "                    if (content) {",
        "                        let rawResult = res.innerText.trim();",
        "                        let formattedResult = rawResult;",
        "                        try {",
        "                            const parsed = JSON.parse(rawResult);",
        "                            let innerContent = parsed.content || parsed;",
        "                            if (typeof innerContent === 'string') {",
        "                                try { innerContent = JSON.parse(innerContent); } catch(e) {}",
        "                            }",
        "                            ",
        "                            if (Array.isArray(innerContent) && innerContent.length > 0 && (innerContent[0].name || innerContent[0].path)) {",
        "                                formattedResult = '<div class=\"file-grid\">' + ",
        "                                    innerContent.map(f => `<div class=\"file-badge ${f.type || 'file'}\"><span class=\"codicon ${f.type === 'directory' ? 'codicon-folder' : 'codicon-file'}\"></span> ${f.name || f.path || 'unknown'}</div>`).join('') + '</div>';",
        "                            } else {",
        "                                formattedResult = '<pre><code>' + JSON.stringify(innerContent, null, 2) + '</code></pre>';",
        "                            }",
        "                        } catch(e) {",
        "                            if (rawResult.length > 500) formattedResult = '<pre><code>' + rawResult.substring(0, 500) + '...</code></pre>';",
        "                            else formattedResult = '<pre><code>' + rawResult + '</code></pre>';",
        "                        }",
        "                        content.innerHTML = '<div class=\"tool-output-label\">Output:</div>' + formattedResult;",
        "                    }",
        "                }",
        "                res.remove();",
        "            });",
        "        }",
        "",
        "        addMessage(role, content, id) {",
        "            const messagesContainer = document.getElementById('messages');",
        "            if (!messagesContainer) return;",
        "            ",
        "            const div = document.createElement('div');",
        "            div.className = `message ${role}`;",
        "            if (id) {",
        "                div.id = id;",
        "                this.assistantMessages[id] = content;",
        "            }",
        "            ",
        "            const contentDiv = document.createElement('div');",
        "            contentDiv.className = 'content';",
        "            contentDiv.innerHTML = this.renderMarkdown(content || '');",
        "            div.appendChild(contentDiv);",
        "            ",
        "            this.finalizeToolCalls(div);",
        "            messagesContainer.appendChild(div);",
        "            this.scrollToBottom();",
        "        }",
        "",
        "        addMessageMetadata(id, metadata) {",
        "            const msgDiv = document.getElementById(id);",
        "            if (!msgDiv) return;",
        "            ",
        "            const metaDiv = document.createElement('div');",
        "            metaDiv.className = 'message-metadata';",
        "            metaDiv.innerHTML = `",
        "                <span>${metadata.model}</span>",
        "                <span>•</span>",
        "                <span>${metadata.tps} t/s</span>",
        "                <span>•</span>",
        "                <span>TTFT: ${metadata.ttft}ms</span>",
        "                <span>•</span>",
        "                <span>In: ${metadata.inputTokens}</span>",
        "                <span>•</span>",
        "                <span>Out: ${metadata.outputTokens}</span>",
        "            `;",
        "            msgDiv.appendChild(metaDiv);",
        "            this.scrollToBottom();",
        "        }",
        "        ",
        "        updateMessage(msg) {",
        "            const msgDiv = document.getElementById(msg.id);",
        "            if (!msgDiv) return;",
        "            const contentDiv = msgDiv.querySelector('.content');",
        "            if (contentDiv) {",
        "                this.assistantMessages[msg.id] = (this.assistantMessages[msg.id] || '') + msg.content;",
        "                contentDiv.innerHTML = this.renderMarkdown(this.assistantMessages[msg.id]);",
        "                this.finalizeToolCalls(msgDiv);",
        "            }",
        "            this.scrollToBottom();",
        "        }",
        "",
        "        scrollToBottom() {",
        "            const container = document.getElementById('messages');",
        "            if (container) container.scrollTop = container.scrollHeight;",
        "        }",
        "",
        "        _updateModels(msg) {",
        "            const select = document.getElementById('model-select');",
        "            if (!select) return;",
        "            ",
        "            const hasModels = msg.models && msg.models.length > 0;",
        "            this._updateInputAvailability(hasModels, msg.loading);",
        "",
        "            select.innerHTML = msg.loading ? '<option>Loading...</option>' : ",
        "                (msg.models.length ? msg.models.map(m => `<option value=\"${m}\" ${m === this.currentModel ? 'selected' : ''}>${m}</option>`).join('') : '<option>No models found</option>');",
        "        }",
        "",
        "        _updateInputAvailability(hasModels, isLoading) {",
        "            const input = document.getElementById('chat-input');",
        "            const btn = document.getElementById('action-button');",
        "            const wrapper = input ? input.closest('.input-wrapper') : null;",
        "            ",
        "            const disabled = !hasModels || isLoading;",
        "            if (input) {",
        "                input.disabled = disabled;",
        "                if (isLoading) {",
        "                    input.placeholder = 'Loading models...';",
        "                } else if (!hasModels) {",
        "                    input.placeholder = 'No models available. Check provider settings.';",
        "                } else {",
        "                    input.placeholder = 'Ask Mosaic...';",
        "                }",
        "            }",
        "            if (btn) btn.disabled = disabled;",
        "            if (wrapper) wrapper.classList.toggle('disabled', disabled);",
        "        }",
        "",
        "        updateChatList(chats) {",
        "            const list = document.getElementById('history-list');",
        "            if (!list) return;",
        "            list.innerHTML = chats.map(c => {",
        "                const date = new Date(c.date).toLocaleDateString(undefined, { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' });",
        "                return `",
        "                <div class=\"history-item\" data-id=\"${c.id}\">",
        "                    <div class=\"history-main\">",
        "                        <div class=\"history-info\">",
        "                            <span class=\"history-name\">${c.name}</span>",
        "                            <span class=\"history-date\">${date}</span>",
        "                        </div>",
        "                        <button class=\"delete-btn\" title=\"Delete Chat\" onclick=\"event.stopPropagation(); this.closest('.history-item').classList.add('confirming')\">",
        "                            <span class=\"codicon codicon-trash\"></span>",
        "                        </button>",
        "                    </div>",
        "                    <div class=\"history-confirm\">",
        "                        <span>Delete this chat?</span>",
        "                        <div class=\"confirm-actions\">",
        "                            <button class=\"confirm-yes\" onclick=\"event.stopPropagation(); vscode.postMessage({ type: 'deleteChat', value: '${c.id}' })\">Delete</button>",
        "                            <button class=\"confirm-no\" onclick=\"event.stopPropagation(); this.closest('.history-item').classList.remove('confirming')\">Cancel</button>",
        "                        </div>",
        "                    </div>",
        "                </div>`;",
        "            }).join('');",
        "        }",
        "",
        "        updateTodoList(todos) {",
        "            const container = document.getElementById('tasks-container');",
        "            const list = document.getElementById('tasks-list');",
        "            if (list) {",
        "                list.innerHTML = todos.length ? todos.map(t => `<div class=\"history-item task-item ${t.status}\">${t.title}</div>`).join('') : '';",
        "            }",
        "            if (container) {",
        "                container.style.display = todos.length ? 'block' : 'none';",
        "            }",
        "        }",
        "",
        "        addSystemMessage(content) {",
        "            const container = document.getElementById('messages');",
        "            if (!container) return;",
        "            const div = document.createElement('div');",
        "            div.className = 'message system';",
        "            div.textContent = content;",
        "            container.appendChild(div);",
        "        }",
        "    }",
        "",
        "    const ui = new MosaicUI();",
        "})();"
    ];
    return lines.join('\\n');
}
